WEB_253504_Kolesnikov.UI/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB_253504_Kolesnikov.Domain.Models;
using WEB_253504_Kolesnikov.UI.Services.ApiMovieService;

namespace WEB_253504_Kolesnikov.UI.Controllers
{
    [Route("[controller]")]
    public class CartController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly Cart _cart;

        public CartController(IMovieService movieService, Cart cart)
        {
            _movieService = movieService;
            _cart = cart;
        }
        public IActionResult Index()
        {
            return View(_cart);
        }

        //[Authorize]
        [Route("[action]/{id:int}")]
        public async Task<IActionResult> Add(int id, string returnUrl)
        {
            var data = await _movieService.GetMovieByIdAsync(id);
            if (data.Successfull)
            {
                _cart.AddToCart(data.Data!);
            }

            return Redirect(returnUrl);

        }

        [Authorize]
        [Route("[action]")]
        public async Task<IActionResult> ClearCart(string returnUrl)
        {
            _cart.ClearAll();
            return Redirect(returnUrl);
        }

        [Authorize]
        [Route("[action]/{id:int}")]
        public async Task<IActionResult> RemoveFromCart(int id, string returnUrl)
        {
            _cart.RemoveItem(id);
            return Redirect(returnUrl);
        }
    }   
}

WEB_253504_Kolesnikov.UI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_253504_Kolesnikov.Domain.Entities;
using WEB_253504_Kolesnikov.Domain.Models;
using WEB_253504_Kolesnikov.UI.Extensions;
using WEB_253504_Kolesnikov.UI.Services.ApiGenreService;
using WEB_253504_Kolesnikov.UI.Services.ApiMovieService;

namespace WEB_253504_Kolesnikov.UI.Controllers
{
    [Route("[controller]")]
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IGenreService _genreService;
        public MovieController(IMovieService movieService, IGenreService genreService) 
        {
            _movieService = movieService;
            _genreService = genreService;
        }
        //[Route("{genre}")]
        [Route("{genre}/{page:int}")]
        public async Task <IActionResult> Index(string? genre, int? page)
        {
            int pageNumber = page ?? 1;
            //if(genre == "all")
            //{
            //    var movieResponse = await 
            //}
            var movieResponse = await _movieService.GetMovieListAsync(genre, pageNumber);
            var genres = await _genreService.GetGenreListAsync();

            if (!movieResponse.Successfull)
                return NotFound(movieResponse.ErrorMessage);
            var currentGenre = genre != "all" ? genres.Data?.Find(g => g.NormalizedName!.Equals(genre))?.Name : "Все";
            ViewData["currentGenre"] = currentGenre;
            Console.WriteLine($"Gerne: {genre}, {currentGenre}");
            ViewData["genres"] = _genreService.GetGenreListAsync().Result.Data;
            ViewData["totalPages"] = movieResponse.Data!.TotalPages;

            var pageViewModel = new ProductListModel<Movie> { Items = movieResponse.Data.Items, CurrentPage = pageNumber, TotalPages = movieResponse.Data.TotalPages };
            if (Request.IsAjaxRequest()) 
            {
                return PartialView("_MovieListPartial", pageViewModel);
            }

            return View(new ProductListModel<Movie> { Items = movieResponse.Data.Items, CurrentPage = 1, TotalPages = 1 });
        }
    }
}

WEB_253504_Kolesnikov.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/lib/font-awesome/css/all.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/site.css")">
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- Меню сайта -->
                <partial name="_MenuPartial"/>
                <!-- Меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserInfoPartial"/>
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
            <span class="nav-color">@* Заголовок страницы *@</span>
        </div>
    </header>
    <main class="container" style="padding: 10px 0px 10px 0px">
        @RenderBody()
    </main>
    <footer>
        <div class="container">
            @* <span class="nav-color">Подвал страницы</span> *@
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fa-brands fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa-brands fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa-brands fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_253504_Kolesnikov.UI/Views/Shared/_Layout_test.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_253504_Kolesnikov.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WEB_253504_Kolesnikov.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- Меню сайта -->
                <a class="navbar-brand" href="#">25350064</a>
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="#">Лб 1</a>
                    <a class="nav-item nav-link" href="#">Каталог</a>
                    <a class="nav-item nav-link" href="#">Администрирование</a>
                </div>
                <!-- Меню сайта - конец -->
                <!-- Информация пользователя -->
                <a href="#" class="navbar-text ms-auto">
                    00,0 руб <i class="fa-solid fa-cart-shopping"></i> (0)
                </a>
                <div class="dropdown ms-4 nav-color">
                    <button class="btn btn-secondary dropdown-toggle"
                            type="button" id="dropdownMenuButton"
                            data-bs-toggle="dropdown"
                            aria-expanded="false">
                        User@gmail.com
                        <img src="images/default-profile-picture.png" width="30" alt="User"
                             class="rounded nav-color" />
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <li>
                            <span class="dropdown-item-text">
                                <img src="images/default-profile-picture.png" width="50" alt="User" class="rounded" />
                                User@gmail.com
                            </span>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <form id="logoutForm" class="form-inline">
                                <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                            </form>
                        </li>
                    </ul>
                </div> <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
            <span class="nav-color">@* Заголовок страницы *@</span>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            @* <span class="nav-color">Подвал страницы</span> *@
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fa-brands fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa-brands fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa-brands fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_253504_Kolesnikov.UI/Views/Shared/_MenuPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower() ?? String.Empty;
    var area = ViewContext.RouteData.Values["area"]?.ToString()?.ToLower() ?? String.Empty;
}
<a asp-controller="Home" asp-action="Index" class="navbar-brand">25350064</a>
<div class="navbar-nav">
    <a asp-area="" asp-controller="Home" asp-action="Index" 
    class="nav-item nav-link @(controller == "home"?"active":"")">Лб 1</a>
    <a asp-area="" asp-controller="Movie" asp-action="Index" asp-route-genre="all" asp-route-page="1", 
    class="nav-item nav-link @(controller == "movie"?"active":"")">Каталог</a>
    <a asp-area="Admin" asp-page="/Product/Index"
    class="nav-item nav-link @(area == "admin"?"active":"")">Администрирование</a>
</div>

WEB_253504_Kolesnikov.UI/Views/Shared/_UserInfoPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@* <a asp-controller="Cart" asp-action="Index" class="navbar-text ms-auto">
    00,0 руб <i class="fa-solid fa-cart-shopping"></i> (0)
</a> *@

@{
    var name = @User
            .Claims
            .FirstOrDefault(c => c.Type.Equals("preferred_username", StringComparison.OrdinalIgnoreCase))?
            .Value;

    var avatar = @User
            .Claims
            .FirstOrDefault(c => c.Type.Equals("avatar", StringComparison.OrdinalIgnoreCase))?
            .Value;
}

@if (User.Identity!.IsAuthenticated)
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ms-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle"
                type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown"
                aria-expanded="false">
            @name
            <img src="@avatar" width="30" alt="User"
                 class="rounded nav-color" />
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
                <span class="dropdown-item-text">
                    <img src="@avatar" width="50" alt="User" class="rounded" />
                    @name
                </span>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form asp-controller="Account" asp-action="Logout" id="logoutForm" class="form-inline">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
}
else
{
    <div class="navbar-nav ms-auto">
        <ul class="nav">
            <li class="nav-item"><a asp-controller="Account" asp-action="Login" class="nav-item nav-link">Login</a></li>
            <li class="nav-item"><a asp-controller="Account" asp-action="Register" class="nav-item nav-link">Register</a></li>
        </ul>
    </div>
}